### ISSUE TITLE
MF info endpoint reports invalid ISIN

### ISSUE THREAD

**Issue by vyomthakkar** [captn3m0/mf.captnemo.in#112]
`/kuvera/:isin` endpoint returns the error `"Invalid ISIN"` even for a valid MF ISIN. Attaching a screenshot to highlight the issue:

<img width="551" alt="Screenshot 2024-02-22 at 5 59 16 PM" src="https://github.com/captn3m0/mf.captnemo.in/assets/28834342/b2cab111-bf00-4781-a027-f1571eab3d27">

Furthermore, the docs webpage says that the schema for the api is documented at https://stoplight.captnemo.in/docs/kuvera/6744709c28f51-mutual-fund-plan-details, however I am unable to access this page. 

Any help with how to use this API would be very highly appreciated! Thanks for doing a great service to the developer community!

**Comment by captn3m0** [comment]
https://captnemo.in/kuvera-unofficial-api-specification/ -> "Mutual Fund Plan Details" (`/mf/api/v4/fund_schemes/{codes}.json`) has the schema. I'll update the README.

**Comment by captn3m0** [comment]
The kuvera data is correct, but the redirect seems to be broken. I'll update once this is fixed.

**Comment by captn3m0** [comment]
Attempted a fix for this, should hopefully fix in another 20 minutes or so.

**Comment by captn3m0** [comment]
Fixed now:

```
curl -I https://mf.captnemo.in/kuvera/INF843K01FC8

HTTP/2 302
access-control-allow-methods: GET
access-control-allow-origin: *
access-control-max-age: 86400
age: 74
cache-control: public,max-age=0,must-revalidate
cache-status: "Netlify Edge"; hit
content-type: application/json
date: Thu, 22 Feb 2024 15:38:29 GMT
location: https://api.kuvera.in/mf/api/v5/fund_schemes/EDPSD1-GR.json
referrer-policy: strict-origin
server: Netlify
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-frame-options: DENY
x-nf-request-id: 01HQ8QFQ4V0TMRG9A0JKT0KW9C
x-xss-protection: 1; mode=block
content-length: 74
```
