### ISSUE TITLE
How to get additional details of the fund?

### ISSUE THREAD

**Issue by ChillarAnand** [captn3m0/mf.captnemo.in#64]
Thanks for providing API for Indian MF.

At the moment, API is providing important stats like AUM, NAV & expense ratio. Is there a possibility to get other details like standard deviation, r-squared, sharpe ratio, portfolio turn over etc?

**Comment by captn3m0** [comment]
Currently no plans for any derived data, as I don't have expertise in that and just dealing with primary data is work enough - I'd rather keep it at low scope and low chance of errors.

While I don't want to work on portfolio turnover specifically, I do want to track Portfolio composition over time. SEBI mandates fortnightly disclosures, which are in a prescribed format. But no guarantees of if/when i get around to it. (Help is welcome!)
